# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlZ4vG8W1TxyOdDJWRjUeMnheeTIUFmU
"""

# first let's make sure you have internet enabled
import requests
requests.get('http://www.google.com',timeout=10).ok

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # ensure we are on the latest version of kaggle-environments
# !pip install --upgrade kaggle-environments

# Now let's set up the chess environment!
from kaggle_environments import make
env = make("chess", debug=True)

# this should run a game in the environment between two random bots
# NOTE: each game starts from a randomly selected opening
result = env.run(["random", "random"])
env.render(mode="ipython", width=1000, height=1000)